class Locator_Path():
    textbox_username_id = "username"
    textbox_password_xpath = "//input[@name='password']"
    button_login_xpath = "//button[@type='submit']"
    button_logout_class_name = "btn btn-danger"
    toggle_menu_xpath = "//*[@id='root']/div/div[2]/header/button[1]"
    File_manager_id = ""
    Exception_Report_id = ""
    button_Book_to_Facs = ""
    button_weekly_Reports = ""
    choosefiles = ""
    Submit = ""
    ExecuteButton = ""
    Status = ""
    BookToFacs = ""
    Submit_BK = ""
    ExecuteButton_BK = ""
    Download_BK = ""
    WeeklyReports = ""
    Submit_WR = ""
    ExecuteButton_WR = ""
    Download_WR = ""

    Logout_Billing = ""
    SelectYear = ""